export const seedSweets = [
  // { name: "Butter Crunch", category: "Boxes", image: "/images/butter-crunch.png", tint: "#E4F1F0",
  //   description: "Buttery crunchy squares topped with roasted almonds, packed in a gift box." },
  // { name: "Chocolate Truffle Cake", category: "Cakes", price: 220, emoji: "🍰", tint: "#E8C7CC",
  //   description: "Dark chocolate sponge layered with silky ganache." },
  // { name: "Butter Croissant", category: "Pastries", price: 120, emoji: "🥐", tint: "#FFE7A8",
  //   description: "Flaky, golden and baked fresh every morning." },
  // { name: "Blueberry Muffin", category: "Pastries", price: 110, emoji: "🧁", tint: "#D9D4F0",
  //   description: "Soft crumb packed with juicy blueberries." },
  // { name: "Choco Chip Cookie", category: "Cookies", price: 80, emoji: "🍪", tint: "#F3D9B8",
  //   description: "Crisp edges, gooey centre, big chocolate chunks." },
  // { name: "Strawberry Donut", category: "Pastries", price: 90, emoji: "🍩", tint: "#F9CBD6",
  //   description: "Pillowy donut with a pink strawberry glaze." },
  // { name: "Vanilla Ice Cream", category: "Cold treats", price: 100, emoji: "🍨", tint: "#FFF1C9",
  //   description: "Slow-churned with real vanilla bean." },
  // { name: "Pistachio Brownie", category: "Cakes", price: 130, emoji: "🍫", tint: "#CFE3C4",
  //   description: "Fudgy brownie topped with crushed pistachios." },
];
